# Generated by Django 5.0.1 on 2024-01-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS', '0005_donor_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Donor_Address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
