# Generated by Django 5.0.1 on 2024-01-24 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS', '0006_donor_donor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Donor_DateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
