# Generated by Django 5.0.1 on 2024-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS', '0007_donor_donor_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Donor_Phone',
            field=models.BigIntegerField(default=10),
        ),
    ]
