# Generated by Django 5.0.1 on 2024-01-25 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS', '0008_alter_donor_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipent',
            name='Receipent_Address',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipent',
            name='Receipent_DateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipent',
            name='Receipent_Email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipent',
            name='Receipent_Hospital',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipent',
            name='Receipent_Phone',
            field=models.BigIntegerField(default=50),
        ),
    ]
